# Numpy Basic

### Consider the below code to answer further questions:

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list = np.array(object=list_, dtype=int)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data types of list_ and array_list. list_ is a Python list containing string elements, while array_list is a NumPy array with elements of the object data type.

In [2]:
# Here's the code to print the data types of both variables:
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'str'>
Data type of array_list: int32


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [3]:
# Here's the code to print the data type of each element in both variables:
for element in list_:
    print("Data type of element in list_:", type(element))
for element in array_list:
    print("Data type of element in array_list:", type(element))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>


#### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Yes, there will be a difference in the data type of the elements present in list_ and array_list after changing the dtype to int in array_list. The elements in list_ are originally strings, while the elements in array_list will be integers after the dtype conversion.

In [4]:
# Here's the code to print the data types of elements in both variables:
array_list = array_list.astype(int)
for element in list_:
    print("Data type of element in list_:", type(element))
for element in array_list:
    print("Data type of element in array_list:", type(element))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>


### Consider the below code to answer further questions:

In [5]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
1. shape
2. size

In [6]:
# Here's the code to find the shape and size of num_array:
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [7]:
# Here's the code to create a 3x3 numpy array containing zeros:
zero_matrix = np.zeros((3, 3))
print("Zero matrix:\n", zero_matrix)

Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
# Here's the code to create an identity matrix of shape (5, 5):
identity_matrix = np.eye(5)
print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
