# TensorFlow Fundamentals

#### **Objective:** The objective of this assignment is to gain practical experience with fundamental operations in TensorFlow, including creating and manipulating matrices, performing arithmetic operations on tensors, and understanding the difference between TensorFlow constants and variables.

<hr style="border: 2px solid black">

#### Part 1: Theoretical Questions
1. What are the different data structures used in TensorFlow? Give some examples.
2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.
3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

<hr style="border: 2px solid black">

#### Part 1: Theoretical Questions
#### Answer 1
TensorFlow primarily uses two data structures:
- **Tensors:** Tensors are multi-dimensional arrays, similar to NumPy arrays, but with additional capabilities for GPU acceleration and distributed computing. Examples include scalars (0-dimensional tensors), vectors (1-dimensional tensors), and matrices (2-dimensional tensors).
- **Graphs:** TensorFlow uses a computational graph to define and execute operations. The graph contains nodes that represent operations and edges that represent the flow of data (tensors) between these operations.

---
#### Answer 2
- **Constant:** TensorFlow constants are used to create tensors with fixed values that cannot be changed during the execution of a computation graph. These values are set when the constant is defined and cannot be modified. For example:
     `constant_tensor = tf.constant([1, 2, 3])`
- **Variable:** TensorFlow variables are used to create tensors whose values can be changed during training or during the execution of a computation graph. Variables are typically used to store model parameters like weights and biases. For example:
     `variable_tensor = tf.Variable([1, 2, 3])`

---
#### Answer 3
- **Matrix Addition:** In TensorFlow, matrix addition is performed using the `tf.add()` function, and it adds corresponding elements of two matrices with the same shape. For example:
     ```
     import tensorflow as tf
     mA = tf.constant([[1, 2], [3, 4]])
     mB = tf.constant([[5, 6], [7, 8]])
     result = tf.add(mA, mB)
     ```
- **Matrix Multiplication:** Matrix multiplication is done with the `tf.matmul()` function, and it computes the dot product of two matrices if they are conformable for multiplication. For example:
     ```
     import tensorflow as tf
     mA = tf.constant([[1, 2], [3, 4]])
     mB = tf.constant([[5, 6], [7, 8]])
     result = tf.matmul(mA, mB)
     ```
- **Element-Wise Operations:** Element-wise operations are performed by applying operations to each element of a tensor independently. For example, element-wise addition can be done using `tf.add()`, and element-wise multiplication can be done using `tf.multiply()`. Here's an example of element-wise multiplication:
     ```
     import tensorflow as tf
     tA = tf.constant([1, 2, 3])
     tB = tf.constant([4, 5, 6])
     result = tf.multiply(tA, tB)
     ```
---

<hr style="border: 2px solid black">

#### Part 2: Practical Implementation

##### Task 1: Creating and Manipulating Matrices
1. Create a normal matrix A with dimensions 2x2, using TensorFlow's `random_normal` function. Display the values of matrix A.
2. Create a Gaussian matrix B with dimensions 2x2, using TensorFlow's `truncated_normal` function. Display the values of matrix B.
3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.x, using TensorFlow's `random.normal` function. Display the values of matrix C.
4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.
##### Task 2: Performing Additional Matrix Operations
1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's `random_uniform` function.
2. Calculate the transpose of matrix F and store the result in matrix G.
3. Calculate the element-wise exponential of matrix F and store the result in matrix H.
4. Create a matrix I by concatenating matrix F and matrix G horizontally.
5. Create a matrix J by concatenating matrix F and matrix H vertically.

<hr style="border: 2px solid black">

In [1]:
import tensorflow as tf

# Task 1 
print("Task 1")
# Task 1.1: Create matrix A with random_normal
mA = tf.random.normal([2, 2], mean=0.0, stddev=1.0, dtype=tf.float32)
print("\nTask 1.1: Matrix A:\n", mA.numpy())
# Task 1.2: Create matrix B with truncated_normal
mB = tf.random.truncated_normal([2, 2], mean=0.0, stddev=1.0, dtype=tf.float32)
print("\nTask 1.2: Matrix B:\n", mB.numpy())
# Task 1.3: Create matrix C with custom normal distribution
mean = 2.0
stddev = 0.1
mC = mean + stddev * tf.random.normal([2, 2], mean=0.0, stddev=1.0, dtype=tf.float32)
print("\nTask 1.3: Matrix C:\n", mC.numpy())
# Task 1.4: Matrix addition (D = A + B)
mD = tf.add(mA, mB)
print("\nTask 1.4: Matrix D (A + B):\n", mD.numpy())
# Task 1.5: Matrix multiplication (E = C * D)
mE = tf.matmul(mC, mD)
print("\nTask 1.5: Matrix E (C * D):\n", mE.numpy())
print('-' * 50)

# Task 2
print("\nTask 2")
# Task 2.1: Create matrix F with random_uniform
mF = tf.random.uniform([2, 2], minval=0.0, maxval=1.0, dtype=tf.float32)
print("\nTask 2.1: Matrix F:\n", mF.numpy())
# Task 2.2: Calculate the transpose (G = transpose(F))
mG = tf.transpose(mF)
print("\nTask 2.2: Matrix G (Transpose of F):\n", mG.numpy())
# Task 2.3: Calculate element-wise exponential (H = exp(F))
mH = tf.exp(mF)
print("\nTask 2.3: Matrix H (Element-wise Exponential of F):\n", mH.numpy())
# Task 2.4: Concatenate matrices horizontally (I = [F, G])
mI = tf.concat([mF, mG], axis=1)
print("\nTask 2.4: Matrix I (Horizontal Concatenation of F and G):\n", mI.numpy())
# Task 2.5: Concatenate matrices vertically (J = [F; H])
mJ = tf.concat([mF, mH], axis=0)
print("\nTask 2.5: Matrix J (Vertical Concatenation of F and H):\n", mJ.numpy())

Task 1

Task 1.1: Matrix A:
 [[-1.4422054  -2.3025773 ]
 [-0.9537724   0.17393608]]

Task 1.2: Matrix B:
 [[ 0.2086432   0.22163787]
 [-0.09355286 -0.08011173]]

Task 1.3: Matrix C:
 [[1.947316  2.053836 ]
 [1.9147822 2.0634754]]

Task 1.4: Matrix D (A + B):
 [[-1.2335622  -2.0809393 ]
 [-1.0473253   0.09382435]]

Task 1.5: Matrix E (C * D):
 [[-4.55317   -3.8595467]
 [-4.523133  -3.7909412]]
--------------------------------------------------

Task 2

Task 2.1: Matrix F:
 [[0.4492612  0.7337972 ]
 [0.47619832 0.9530691 ]]

Task 2.2: Matrix G (Transpose of F):
 [[0.4492612  0.47619832]
 [0.7337972  0.9530691 ]]

Task 2.3: Matrix H (Element-wise Exponential of F):
 [[1.5671539 2.0829751]
 [1.6099423 2.5936577]]

Task 2.4: Matrix I (Horizontal Concatenation of F and G):
 [[0.4492612  0.7337972  0.4492612  0.47619832]
 [0.47619832 0.9530691  0.7337972  0.9530691 ]]

Task 2.5: Matrix J (Vertical Concatenation of F and H):
 [[0.4492612  0.7337972 ]
 [0.47619832 0.9530691 ]
 [1.5671539  2.082